version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    networks:
      - wpsite
    restart: always
  
  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    env_file: .env
    networks:
      - wpsite
    restart: always
  
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp-site
    ports:
      - "8000:80"
    volumes:
      - wp_data:/var/www/html
    env_file: .env
    networks:
      - wpsite
    restart: always

volumes:
  db_data:
    driver: local
    name: db_data_volume
    driver_opts:
      o: bind
      type: none
      device: ~/Documents/WORDPRESS_SITE/mysql_data

  wp_data:
    driver: local
    name: wp_data_volume
    driver_opts:
      o: bind
      type: none
      device: ~/Documents/WORDPRESS_SITE/wordpress_data

networks:
  wpsite:
    driver: bridge
    name: wpsite_network
